DESC TBL_SCORE;

-- ¼ºÀû ÀÔ·Â
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT)
VALUES(SCORESEQ.NEXTVAL, '±è½Â¹ü', 33, 44, 55);
-->
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '±è½Â¹ü', 33, 44, 55)
;


-- ÀüÃ¼ Ãâ·Â
SELECT SID, NAME, KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT
     , (KOR + ENG + MAT) / 3 AS AVG
     , RANK() OVER (ORDER BY (KOR + ENG + MAT)) AS RANK
FROM TBL_SCORE;
-->
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT) / 3 AS AVG, RANK() OVER (ORDER BY (KOR + ENG + MAT)) AS RANK FROM TBL_SCORE
;


-- °Ë»ö Ãâ·Â
SELECT SID, NAME, KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT
     , (KOR + ENG + MAT) / 3 AS AVG
     , RANK() OVER (ORDER BY (KOR + ENG + MAT)) AS RANK
FROM TBL_SCORE
WHERE NAME = '±è½Â¹ü';
-->
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT) / 3 AS AVG, RANK() OVER (ORDER BY (KOR + ENG + MAT)) AS RANK FROM TBL_SCORE WHERE NAME = '±è½Â¹ü'
;


-- ¼öÁ¤
UPDATE TBL_SCORE
--SET NAME = '°­½Â±¸'
  , KOR = '99', ENG = '99', MAT = '99'
WHERE WHERE SID = '1';
-->
UPDATE TBL_SCORE SET NAME = '°­½Â±¸', KOR = '99', ENG = '99', MAT = '99' WHERE SID = '1'
;


-- »èÁ¦
DELETE FROM TBL_SCORE WHERE SID = 0
;



     