SELECT USER
FROM DUAL;

-- 김승범, 이예슬
-- 학생, 관리자, 수강신청, 중도탈락자, 성적

-- 관리자 테이블
CREATE TABLE ADMIN
( ADM_ID  VARCHAR2(15)  PRIMARY KEY
, PW      VARCHAR2(20) -- 디폴트값으로 JUBUN을 줘야함
, JUBUN   CHAR(7)      -- NOT NULL..
);

ALTER TABLE ADMIN
ADD CONSTRAINT ADM_JUBUN_NN  CHECK(JUBUN IS NOT NULL);

ALTER TABLE ADMIN
MODIFY PW VARCHAR2(20) DEFAULT JUBUN;

-- 중도 탈락자
CREATE TABLE DROPOUT
( DR_CODE  VARCHAR2(10)  PRIMARY KEY
, RC_CODE  VARCHAR2(10)  -- REGISTER_COURSES 외래키
, DR_DATE  DATE          -- DEFAULT로 SYSDATE?
, DR_REASON VARCHAR2(100) -- NOT NULL?
);

ALTER TABLE DROPOUT
ADD CONSTRAINT DR_RC_CODE_FK FOREIGN KEY (RC_CODE)
               REFERENCES TO REGISTER_COURSES(RC_CODE);

ALTER TABLE DROPOUT
MODIFY DR_DATE DATE DEFAULT SYSDATE;

-- 성적
CREATE TABLE RESULTS
( RE_CODE                   VARCHAR2(10)  PRIMARY KEY
, RC_CODE                   VARCHAR2(10)  -- REGISTER_COURSES 외래키
, OS_CODE                   VARCHAR2(10)  -- OPEN_SUBJECTS 외래키
, RE_DATE                   DATE          -- DEFAULT로 SYSDATE?
, ATD_RESULT                NUMBER(3)     -- NOT NULL
, PRC_RESULT                NUMBER(3)     -- NOT NULL
, WRT_RESULT                NUMBER(3)     -- NOT NULL
);

ALTER TABLE RESULTS
ADD ( CONSTRAINT R_RC_CODE_FK FOREIGN KEY (RC_CODE)
               REFERENCES TO REGISTER_COURSES(RC_CODE)
    , CONSTRAINT R_OS_CODE_FK FOREIGN KEY (OS_CODE)
               REFERENCES TO OPEN_SUBJECTS(OS_CODE)
);

ALTER TABLE RESULTS
MODIFY RE_DATE DATE DEFAULT SYSDATE;
               
               
               