--○ 실습 테이블
DESC TBL_SCORE;


-- 추가
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) 
VALUES (SCORESEQ.NEXTVAL, '이름', '국어', '영어', '수학');
--> 한줄 구성
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES (SCORESEQ.NEXTVAL, '이름', '국어', '영어', '수학')
;

-- 조회
SELECT NAME, KOR, ENG, MAT
    , (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG
    , RANK() OVER (ORDER BY (KOR+ENG+MAT) DESC) AS RANK 
FROM TBL_SCORE;
--> 한줄 구성
SELECT NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG, RANK() OVER (ORDER BY (KOR+ENG+MAT) DESC) AS RANK FROM TBL_SCORE
;







