SELECT USER
FROM DUAL;


CREATE USER MANAGER
IDENTIFIED BY java006$;
--==>> User MANAGER이(가) 생성되었습니다.

GRANT SYSDBA TO MANAGER;
--==>> Grant을(를) 성공했습니다.

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO MANAGER;
--==>> Grant을(를) 성공했습니다.

ALTER USER MANAGER DEFAULT TABLESPACE USERS;
--==>> User MANAGER이(가) 변경되었습니다.

ALTER USER MANAGER TEMPORARY TABLESPACE TEMP;
--==>> User MANAGER이(가) 변경되었습니다.


REVOKE SYSDBA FROM MANAGER;
