SELECT USER
FROM DUAL;

CREATE TABLE TBL_STUDENT
(
  SID           NUMBER           -- PK
, NAME          VARCHAR2(30) 
, TEL    	    VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);

CREATE TABLE TBL_GRADE
(
  SID          NUMBER           -- PK / FK
, SUB1         NUMBER(3) 
, SUB2    	   NUMBER(3)
, SUB3		   NUMBER(3)
, CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)
             REFERENCES TBL_STUDENT(SID)
);

CREATE OR REPLACE VIEW STUDENTVIEW 
AS
SELECT S.SID, S.NAME, S.TEL
     , (SELECT COUNT(*)
        FROM TBL_GRADE G
        WHERE G.SID = S.SID) AS SUB
FROM TBL_STUDENT S
ORDER BY SID;


CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID
     , NAME
     , SUB1, SUB2, SUB3
     , (SUB1 + SUB2 + SUB3) AS TOT
     , (SUB1 + SUB2 + SUB3)/3 AS AVG
     , (CASE WHEN (SUB1 + SUB2 + SUB3)/3 >= 60 THEN '합격'
             WHEN (SUB1 + SUB2 + SUB3)/3 > 40 THEN '불합격'
             ELSE '과락'
             END) AS CH
FROM TBL_GRADE G, TBL_STUDENT S
WHERE G.SID = S.SID
ORDER BY S.SID;


-- STUDENT 관련 쿼리문
CREATE SEQUENCE SID_SEQ
NOCACHE;

-- 추가
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(SID_SEQ.NEXTVAL, '김승범', '010-3441-0260');
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(SID_SEQ.NEXTVAL, '권소윤', '010-1111-2222');
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(SID_SEQ.NEXTVAL, '조윤상', '010-3333-4444');

-->
INSERT INTO TBL_STUDENT VALUES(SID_SEQ.NEXTVAL, ?, ?)
;

-- 조회
SELECT SID, NAME, TEL, SUB
FROM STUDENTVIEW;

-- 수정
UPDATE TBL_STUDENT
SET NAME = '이승범'
  , TEL = '010-3377-6108'
WHERE SID = 1;
-->
UPDATE TBL_STUDENT SET NAME = ?, TEL = ? WHERE SID = ?;

-- 삭제
DELETE
FROM TBL_STUDENT 
WHERE SID = 1
  AND (SELECT SUB
       FROM STUDENTVIEW V
       WHERE V.SID = 1) = 0;
-->
DELETE FROM TBL_STUDENT WHERE SID = ?
;

-- 갯수
SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;

-- 찾기
SELECT SID, NAME, TEL
FROM TBL_STUDENT
WHERE SID = 1;




-- GRADE 관련 쿼리문
-- 추가
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 100, 100, 100);

-- 조회
SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW
ORDER BY SID;

-- 수정
UPDATE TBL_GRADE
SET SUB1 = 100
, SUB2 = 100
, SUB3 = 100
WHERE SID = 1;

-- 삭제
DELETE 
FROM TBL_GRADE
WHERE SID = 1;

-- 갯수
SELECT COUNT(*) AS COUNT
FROM TBL_GRADE;

-- 찾기
SELECT SID, SUB1, SUB2, SUB3
FROM TBL_GRADE
WHERE SID = 1;


